sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (sprite, otherSprite) {
    info.startCountdown(2)
    donuts.setPosition(randint(0, 100), randint(0, 100))
    info.changeScoreBy(1)
})
let donuts: Sprite = null
let homer = sprites.create(img`
    ..............................
    ...........fffffff............
    ..........f.f....ff...........
    .........f.f......ff..........
    ........ffffffffffff..........
    .......f555555555555f.........
    ......f55ffff5ffff555f........
    ......f5f1111f1111f55f........
    ......f5f1ff1f1ff1f55f........
    ......f5f1ff1f1ff1f55f........
    ......f5f1111f1111f55f........
    ......f55ffff5ffff555f........
    ......f55555555555555f........
    ......f55555555555555f........
    ......f55555555555555f........
    ......f5ffffffffffff5f........
    ......fffddddddddddfff........
    ......fddddddddddddddf........
    ......fddddddddddddddf........
    ......fddffdddddffdddf........
    ......fdddfffffffddddf........
    ......fdddddff333fdddf........
    .......fdddddff33fddf.........
    ........fdddddffffdf..........
    .........fddddddfff...........
    ..........ffffffff............
    ..............................
    ..............................
    ..............................
    ..............................
    `, SpriteKind.Player)
donuts = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . f f f f f f f f f f . . . 
    . . f 3 5 3 3 3 3 3 3 3 3 f . . 
    . f 3 3 5 3 f f f f 3 3 5 3 f . 
    . f 3 3 3 f . . . . f 3 5 3 f . 
    . f 3 3 3 3 f f f f 3 3 3 3 f . 
    . f 3 5 3 3 3 3 3 3 3 5 3 3 f . 
    . f 3 3 5 3 3 3 3 3 5 3 3 3 f . 
    . . f 3 3 3 3 3 3 3 3 3 3 f . . 
    . . . f f f f f f f f f f . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Food)
controller.moveSprite(homer)
scene.setBackgroundColor(9)
