sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (sprite, otherSprite) {
    info.changeScoreBy(1)
    donuts.setPosition(randint(0, 100), randint(0, 100))
    info.changeCountdownBy(1)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    game.gameOver(false)
})
let donuts: Sprite = null
game.splash("Eat the donuts with Homer")
let myMenu = miniMenu.createMenu(
miniMenu.createMenuItem("mmmh the donuts")
)
myMenu.setPosition(77, 112)
let homer = sprites.create(img`
    ..............................
    ...........fffffff............
    ..........f.f....ff...........
    .........f.f......ff..........
    ........ffffffffffff..........
    .......f555555555555f.........
    ......f55ffff5ffff555f........
    ......f5f1111f1111f55f........
    ......f5f1ff1f1ff1f55f........
    ......f5f1ff1f1ff1f55f........
    ......f5f1111f1111f55f........
    ......f55ffff5ffff555f........
    ......f55555555555555f........
    ......f55555555555555f........
    ......f55555555555555f........
    ......f5ffffffffffff5f........
    ......fffddddddddddfff........
    ......fddddddddddddddf........
    ......fddddddddddddddf........
    ......fddffdddddffdddf........
    ......fdddfffffffddddf........
    ......fdddddff333fdddf........
    .......fdddddff33fddf.........
    ........fdddddffffdf..........
    .........fddddddfff...........
    ..........ffffffff............
    ..............................
    ..............................
    ..............................
    ..............................
    `, SpriteKind.Player)
donuts = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . f f f f f f f f f f . . . 
    . . f 3 5 3 3 3 3 3 3 3 3 f . . 
    . f 3 3 5 3 f f f f 3 3 5 3 f . 
    . f 3 3 3 f . . . . f 3 5 3 f . 
    . f 3 3 3 3 f f f f 3 3 3 3 f . 
    . f 3 5 3 3 3 3 3 3 3 5 3 3 f . 
    . f 3 3 5 3 3 3 3 3 5 3 3 3 f . 
    . . f 3 3 3 3 3 3 3 3 3 3 f . . 
    . . . f f f f f f f f f f . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Food)
let OPERATORE = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    ........................
    ..........ffff..........
    ........ff1111ff........
    .......fb111111bf.......
    .......f11111111f.......
    ......fd11111111df......
    ....7.fd11111111df......
    ...7..fd11111111df......
    ...7..fd11111111df......
    ...7..fddd1111dddff.....
    ...77.fbdbfddfbdbfcf....
    ...777fcdcf11fcdcfbf....
    ....77fffbdb1bdffcf.....
    ....fcb1bcffffff........
    ....f1c1c1ffffff........
    ....fdfdfdfffff.........
    .....f.f.f..............
    ........................
    ........................
    ........................
    `, SpriteKind.Enemy)
info.setScore(0)
OPERATORE.setPosition(149, 106)
controller.moveSprite(homer)
scene.setBackgroundColor(9)
homer.setBounceOnWall(true)
OPERATORE.follow(homer, 50)
donuts.setPosition(randint(16, 84), randint(16, 84))
info.startCountdown(10)
forever(function () {
    OPERATORE.setBounceOnWall(true)
})
